//
//  JDCommonConstant.m
//  JDYunCardSDK
//
//  Created by xiaoyi li on 16/9/21.
//  Copyright © 2016年 xiaoyi li. All rights reserved.
//


#import "JDCommonConstant.h"

@implementation JDCommonConstant

NSString *const JD_YUN_CARD_SDK_VER = @"1.0.0";
NSString *const SERVER_URL = @"";
NSString *const CERT_REQUEST = @"-----BEGIN CERTIFICATE REQUEST-----MIIB2DCCAUECAQAwgYAxCzAJBgNVBAYTAmNuMRIwEAYDVQQIEwlHdWFuZ0RvbmcxEjAQBgNVBAcTCUd1YW5nemhvdTEMMAoGA1UEChMDcGNpMQ0wCwYDVQQLEwRkYXRhMQswCQYDVQQDEwJwZDEfMB0GCSqGSIb3DQEJARYQbGl4aWFveWlAMTYzLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAsY6qfSwkLjJLRlYRIcQ3KYGVPUckg3fIZd2pr0CI3GHaAuQt0wQ1QBa+bYdttZ89p0JslkfaNYWfDM6g0fnY1dBzmvtJaZ4MDlUWh0ydgunKojVIIfQyM1uRvTwJMPJWRx2ofo/xkFv+I57dGaHJsrsXF99r9TJS355OBCkbgWsCAwEAAaAXMBUGCSqGSIb3DQEJBzEIEwYxMjM0NTYwDQYJKoZIhvcNAQEFBQADgYEATHrftpOWe188mBOyItYZhOF5Zruk719M+5XBuqWc9Rjb7bVY11e2KmS/GmOPUeL7g3cxGC43fBiTGCgIn+sd2TZ2ZZJ+BM+2mZbMvYGwkSW4Q0WPEDSNrXiZzDmiU1trHczmaYyC/rVHyIFDGZye/izlNi769CLi7Q2I1/ya4x4=-----END CERTIFICATE REQUEST-----";
NSString *const CERT_REQUEST_HEADER = @"-----BEGIN CERTIFICATE REQUEST-----";
NSString *const CERT_REQUEST_FOOTER = @"-----END CERTIFICATE REQUEST-----";

@end
